# Generated by Django 6.0.5 on 2026-05-28 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_remove_dashboard_nav_item"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="units",
        ),
    ]
