# Generated by Django 6.0.5 on 2026-05-28 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_remove_profile_units"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="goal_weight_kg",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Goal Weight (kg)"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="height_cm",
            field=models.FloatField(blank=True, null=True, verbose_name="Height (cm)"),
        ),
        migrations.AddField(
            model_name="profile",
            name="theme",
            field=models.CharField(
                choices=[("light", "Light"), ("dark", "Dark")],
                default="light",
                max_length=10,
            ),
        ),
    ]
