# Generated by Django 6.0.5 on 2026-05-28 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_profile_goal_weight_kg_profile_height_cm_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="nav_color",
            field=models.CharField(
                choices=[
                    ("blue", "Blue"),
                    ("slate", "Slate"),
                    ("emerald", "Emerald"),
                    ("violet", "Violet"),
                    ("amber", "Amber"),
                    ("rose", "Rose"),
                    ("cyan", "Cyan"),
                    ("stone", "Stone"),
                ],
                default="blue",
                max_length=10,
            ),
        ),
    ]
