# Generated by Django 6.0.5 on 2026-05-29 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_profile_nav_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="theme",
            field=models.CharField(
                choices=[
                    ("light", "Light"),
                    ("dark", "Dark"),
                    ("auto", "Auto (follow system)"),
                ],
                default="light",
                max_length=10,
            ),
        ),
    ]
