# Generated by Django 6.0.5 on 2026-05-29 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_add_cardio_nav_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="sex",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")],
                default="male",
                max_length=6,
            ),
        ),
    ]
