# Generated by Django 6.0.5 on 2026-05-30 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_add_importexport_nav_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="goal_body_fat_pct",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Goal Body Fat (%)"
            ),
        ),
    ]
