# Generated by Django 6.0.5 on 2026-05-30 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_profile_goal_body_fat_pct"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="units",
            field=models.CharField(
                choices=[
                    ("metric", "Metric (kg/cm)"),
                    ("imperial", "Imperial (lbs/in)"),
                ],
                default="imperial",
                max_length=10,
            ),
        ),
    ]
