# Generated by Django 6.0.5 on 2026-05-22 14:39

import django.db.models.deletion
import photos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to=photos.models.photo_path)),
                ('body_part', models.CharField(choices=[('front', 'Front'), ('back', 'Back'), ('left_side', 'Left Side'), ('right_side', 'Right Side'), ('other', 'Other')], default='front', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Progress photos',
                'ordering': ['-date', '-uploaded_at'],
            },
        ),
    ]
