# Generated by Django 6.0.5 on 2026-05-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workoutexercise",
            name="target_reps_max",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workoutexercise",
            name="target_reps_min",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workoutexercise",
            name="target_sets",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workouttemplateexercise",
            name="target_reps_max",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workouttemplateexercise",
            name="target_reps_min",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
