# Generated by Django 6.0.5 on 2026-05-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_workoutexercise_target_reps_max_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="exercises", to="tracker.exercisecategory"
            ),
        ),
    ]
