# Generated by Django 6.0.5 on 2026-05-24 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0004_copy_category_to_categories"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exercise",
            name="category",
        ),
    ]
