# Generated by Django 6.0.5 on 2026-05-24 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0005_remove_category_fk"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="set",
            name="rir",
        ),
    ]
