# Generated by Django 6.0.5 on 2026-05-30 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0007_cardiolog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workouttemplateexercise",
            name="target_weight_kg",
        ),
    ]
