# Generated by Django 6.0.5 on 2026-05-30 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0008_remove_workouttemplateexercise_target_weight_kg"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="workouttemplate",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
