# Generated by Django 6.0.5 on 2026-05-30 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0009_exercise_is_public_workouttemplate_is_public"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BodyFatLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("body_fat_pct", models.FloatField(verbose_name="Body Fat %")),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("navy", "US Navy (calculated)"),
                            ("caliper", "Caliper"),
                            ("dexa", "DEXA Scan"),
                            ("bodpod", "Bod Pod"),
                            ("scale_bia", "Bioimpedance Scale"),
                            ("photo_3d", "3D Photo Scan"),
                            ("manual", "Manual Entry"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="body_fat_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
                "unique_together": {("user", "date")},
            },
        ),
    ]
