# Generated by Django 6.0.5 on 2026-05-30 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0010_bodyfatlog"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="bodyfatlog",
            unique_together=set(),
        ),
    ]
