# Generated by Django 6.0.5 on 2026-06-09 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0011_alter_bodyfatlog_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
