# Generated by Django 6.0.5 on 2026-06-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0012_workout_started_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="set",
            name="completed",
            field=models.BooleanField(default=False),
        ),
    ]
